### ISSUE TITLE
Verification of the created field is too strict

### ISSUE THREAD

**Issue by achille-roussel** [pyauth/http-message-signatures#10]
Hello!

I am opening this issue to discuss an improvement that could be made to the `created` timestamp verification.

It's been our experience that even when clocks are in sync between systems in low-latency networks, the client might cross a 1-second boundary before the server, which then mistakenly refuses the signature claiming that the timestamp is in the future; because of this check https://github.com/pyauth/http-message-signatures/blob/main/http_message_signatures/signatures.py#L135-L138

```python
        now = datetime.datetime.now()
        if "created" in sig_input.params:
            if self._parse_integer_timestamp(sig_input.params["created"], field_name="created") > now:
                raise InvalidSignature('Signature "created" parameter is set to a time in the future')
```

As a workaround, we can disable setting the `created` field on the client side, but this isn't ideal.

An alternative could be introducing a tolerance in comparing the `created` timestamp and `now`. For example, a 1-second default tolerance should cover most use cases without significantly reducing safety. Making this configurable could also be a useful improvement if a default isn't desired.

I'm happy to send a pull request to submit the fix; let me know what you think!

**Comment by kislyuk** [comment]
Hi, thanks for pointing this out. You are correct, this part of the verification process needs a "max clock skew" parameter. It's unclear what the default should be; I would be comfortable starting with a default of 30 seconds. There's a good argument to be made that there shouldn't be a default set at all and that the user should be forced to set a value to be aware of it, but I think the ergonomic downside of this outweighs the security upside.

PRs are very welcome for this.
