### ISSUE TITLE
Test.py does not use key pair test-key-rsa.pem?

### ISSUE THREAD

**Issue by chrisinmtown** [pyauth/http-message-signatures#3]
I am trying to use a plain RSA public/private key pair to sign a message (not an RSA-PSS pair). I hit problems and looked at test.py for how it loads the public and private keys from files test-key-rsa.pem, test-key-rsa.key.  Then I realized, those files are not currently used in a test. Please tell me, is that just an oversight, or is there something about plain (non-PSS) RSA keys that makes this impossible?

If I succeed in creating a test I'll post the code here.

**Comment by kislyuk** [comment]
That's correct. The test directory contains all example key material from
the RFC/draft standard, but that particular key is only used in the proxy
passthrough signature example, which we do not currently test for. So that
key is not in use.
